export type Category = "All" | "Anime" | "Gaming" | "Nature" | "Movies" | "Artists" | "Abstract" | "Music"

export interface Product {
  id: string
  title: string
  artist: string
  category: Category
  price: number
  originalPrice?: number
  image: string
  images?: string[]
  description: string
  sizes: string[]
  materials: string[]
  onSale: boolean
  featured: boolean
}

export const categories: Category[] = [
  "All",
  "Anime",
  "Gaming",
  "Nature",
  "Movies",
  "Artists",
  "Abstract",
  "Music",
]

export const products: Product[] = [
  {
    id: "p1",
    title: "Neon Samurai",
    artist: "Yuki Tanaka",
    category: "Anime",
    price: 29,
    originalPrice: 39,
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&h=600&fit=crop",
    description: "A breathtaking fusion of traditional samurai aesthetics with cyberpunk neon lighting. This poster captures the essence of modern anime art with vivid electric blues and deep shadows.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: true,
  },
  {
    id: "p2",
    title: "Cyber Dragon",
    artist: "Hiro Matsuda",
    category: "Anime",
    price: 34,
    image: "https://images.unsplash.com/photo-1541562232579-512a21360020?w=600&h=600&fit=crop",
    description: "A massive mechanical dragon soaring through a neon-lit cityscape. Intricate detail meets bold anime style in this stunning wall art piece.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p3",
    title: "Spirit Garden",
    artist: "Sakura Ito",
    category: "Anime",
    price: 27,
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&h=600&fit=crop",
    description: "A serene garden inhabited by ethereal spirits, painted in soft watercolor tones with anime-inspired character design.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p4",
    title: "Tokyo Drift",
    artist: "Ken Nakamura",
    category: "Anime",
    price: 32,
    originalPrice: 42,
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=600&h=600&fit=crop",
    description: "Speeding through the neon streets of Tokyo in a souped-up JDM classic. Anime car culture meets cityscape art.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p5",
    title: "Pixel Battleground",
    artist: "Alex Chen",
    category: "Gaming",
    price: 31,
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=600&fit=crop",
    description: "A retro pixel art battlefield brought to life with modern color grading. Perfect for any gamer's setup.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: true,
  },
  {
    id: "p6",
    title: "Controller Dreams",
    artist: "Maya Rodriguez",
    category: "Gaming",
    price: 26,
    image: "https://images.unsplash.com/photo-1592155931584-901ac15763e3?w=600&h=600&fit=crop",
    description: "A dreamy, surreal composition built around iconic gaming controllers floating in a cosmic void.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p7",
    title: "Boss Fight",
    artist: "Jake Morrison",
    category: "Gaming",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&h=600&fit=crop",
    description: "An epic boss encounter rendered in stunning detail. The dragon looms above as the hero readies their blade.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p8",
    title: "Retro Arcade",
    artist: "Sam Lee",
    category: "Gaming",
    price: 28,
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=600&fit=crop",
    description: "Step into a glowing retro arcade with rows of classic cabinets. Nostalgic vibes and vibrant neon colors.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p9",
    title: "Mountain Serenity",
    artist: "Elara Voss",
    category: "Nature",
    price: 33,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=600&fit=crop",
    description: "Snow-capped peaks bathed in golden sunrise light. A calming piece that brings the grandeur of nature indoors.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: true,
  },
  {
    id: "p10",
    title: "Ocean Depths",
    artist: "Liam Waters",
    category: "Nature",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=600&h=600&fit=crop",
    description: "Dive into the mesmerizing deep blue ocean with sunlight streaming through the surface. Peaceful and powerful.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p11",
    title: "Aurora Dreams",
    artist: "Nina Frost",
    category: "Nature",
    price: 36,
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&h=600&fit=crop",
    description: "The Northern Lights dancing across an arctic sky in vivid greens and blues. A premium print for nature lovers.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p12",
    title: "Rainforest Canopy",
    artist: "Diego Silva",
    category: "Nature",
    price: 29,
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&h=600&fit=crop",
    description: "Looking up through the dense canopy of a tropical rainforest. Layers of green create a hypnotic pattern.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p13",
    title: "Cinema Noir",
    artist: "Frank Ricci",
    category: "Movies",
    price: 34,
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&h=600&fit=crop",
    description: "A tribute to classic film noir. Dramatic shadows, a lone figure, and the glow of a neon sign set the scene.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p14",
    title: "Sci-Fi Odyssey",
    artist: "Nova Kim",
    category: "Movies",
    price: 38,
    originalPrice: 48,
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=600&fit=crop",
    description: "A sweeping sci-fi landscape inspired by the greatest space epics. A lone spacecraft approaches an unknown planet.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: true,
  },
  {
    id: "p15",
    title: "Western Sunset",
    artist: "Clint Harper",
    category: "Movies",
    price: 31,
    image: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=600&h=600&fit=crop",
    description: "A dusty western landscape with a lone rider silhouetted against a blazing sunset. Cinematic and iconic.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p16",
    title: "Horror Classics",
    artist: "Vera Shade",
    category: "Movies",
    price: 27,
    image: "https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=600&h=600&fit=crop",
    description: "A dark, atmospheric piece inspired by vintage horror movie posters. Eerie shadows and a haunting presence.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p17",
    title: "Abstract Flow",
    artist: "Iris Chroma",
    category: "Artists",
    price: 42,
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&h=600&fit=crop",
    description: "A signature piece from Iris Chroma. Flowing colors and organic shapes create a mesmerizing visual experience.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: true,
  },
  {
    id: "p18",
    title: "Urban Canvas",
    artist: "Rex Street",
    category: "Artists",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1561214078-f3247647fc5e?w=600&h=600&fit=crop",
    description: "Street art meets fine art. Bold graffiti-inspired strokes on a textured urban background.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p19",
    title: "Digital Portrait",
    artist: "Luna Byte",
    category: "Artists",
    price: 37,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=600&fit=crop",
    description: "A stunning digital portrait that blurs the line between photography and painting. Hyper-detailed and ethereal.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p20",
    title: "Minimalist Lines",
    artist: "Kai Simple",
    category: "Artists",
    price: 25,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=600&fit=crop",
    description: "Elegant minimalist line art. Clean, sophisticated, and perfect for modern living spaces.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p21",
    title: "Geometric Pulse",
    artist: "Vector Prime",
    category: "Abstract",
    price: 33,
    image: "https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=600&h=600&fit=crop",
    description: "Pulsating geometric shapes in a hypnotic pattern. Bold colors clash and harmonize in this abstract masterpiece.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p22",
    title: "Color Explosion",
    artist: "Burst Studio",
    category: "Abstract",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&h=600&fit=crop",
    description: "An explosion of color captured in paint. Dynamic splashes create an energetic and uplifting atmosphere.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p23",
    title: "Dark Matter",
    artist: "Void Collective",
    category: "Abstract",
    price: 39,
    image: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=600&h=600&fit=crop",
    description: "Deep blacks and subtle color shifts evoke the mystery of dark matter. A premium piece for sophisticated spaces.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p24",
    title: "Fluid Motion",
    artist: "Aqua Arts",
    category: "Abstract",
    price: 28,
    image: "https://images.unsplash.com/photo-1567095761054-7a02e69e5b2b?w=600&h=600&fit=crop",
    description: "Liquid art frozen in time. Smooth gradients and organic shapes flow across the canvas in mesmerizing patterns.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p25",
    title: "Jazz Session",
    artist: "Miles Blue",
    category: "Music",
    price: 34,
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&h=600&fit=crop",
    description: "The smoky atmosphere of a late-night jazz club captured in rich, warm tones. You can almost hear the saxophone.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p26",
    title: "Electric Stage",
    artist: "Amp Visuals",
    category: "Music",
    price: 31,
    originalPrice: 41,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=600&fit=crop",
    description: "The raw energy of a live concert stage. Spotlights, haze, and the electric anticipation of a sold-out show.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p27",
    title: "Vinyl Dreams",
    artist: "Analog Soul",
    category: "Music",
    price: 27,
    image: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=600&h=600&fit=crop",
    description: "A beautiful close-up of a vinyl record spinning on a turntable. Warm tones and analog nostalgia.",
    sizes: ["M (12x16)", "L (18x24)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
  {
    id: "p28",
    title: "Moonlit Peak",
    artist: "Elara Voss",
    category: "Nature",
    price: 35,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&h=600&fit=crop",
    description: "A dramatic mountain peak illuminated by moonlight. The stark contrast between shadow and light creates an awe-inspiring scene.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p29",
    title: "Mech Warrior",
    artist: "Hiro Matsuda",
    category: "Anime",
    price: 36,
    originalPrice: 46,
    image: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?w=600&h=600&fit=crop",
    description: "A towering mech suit stands guard over a futuristic city. Detailed mechanical design meets epic anime composition.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: true,
    featured: false,
  },
  {
    id: "p30",
    title: "Dungeon Master",
    artist: "Alex Chen",
    category: "Gaming",
    price: 33,
    image: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=600&h=600&fit=crop",
    description: "A tabletop RPG-inspired composition with dice, maps, and mystical creatures. Every gamer's fantasy brought to life.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p31",
    title: "Galactic Empire",
    artist: "Nova Kim",
    category: "Movies",
    price: 36,
    image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&h=600&fit=crop",
    description: "A sprawling space empire rendered in stunning detail. Massive ships orbit a distant sun in this cinematic piece.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper", "Metal Print"],
    onSale: false,
    featured: false,
  },
  {
    id: "p32",
    title: "Sound Waves",
    artist: "Miles Blue",
    category: "Music",
    price: 29,
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=600&fit=crop",
    description: "Abstract sound waves visualized as flowing ribbons of color. Music made visible in this unique art piece.",
    sizes: ["M (12x16)", "L (18x24)", "XL (24x36)"],
    materials: ["Matte Paper", "Glossy Paper"],
    onSale: false,
    featured: false,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: Category): Product[] {
  if (category === "All") return products
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getSaleProducts(): Product[] {
  return products.filter((p) => p.onSale)
}

export function getRelatedProducts(product: Product, limit = 6): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit)
}

export function getFirstProductByCategory(category: Category): Product | undefined {
  if (category === "All") return products[0]
  return products.find((p) => p.category === category)
}
