-- Enhanced Waitlist Schema Migration
-- Adds constraints, indexes, and audit columns for production readiness

-- Add unique constraint to prevent duplicate signups for same product
ALTER TABLE public.waitlist_entries
ADD CONSTRAINT unique_email_product UNIQUE(email, product_id);

-- Add email format validation at database level
ALTER TABLE public.waitlist_entries
ADD CONSTRAINT valid_email_format 
CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$');

-- Add updated_at column for audit trail
ALTER TABLE public.waitlist_entries
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Create trigger function to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS update_waitlist_entries_updated_at ON public.waitlist_entries;
CREATE TRIGGER update_waitlist_entries_updated_at
BEFORE UPDATE ON public.waitlist_entries
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Add index on created_at for sorting/filtering recent signups
CREATE INDEX IF NOT EXISTS idx_waitlist_created_at ON public.waitlist_entries(created_at DESC);

-- Add composite index for common queries (product_id + created_at)
CREATE INDEX IF NOT EXISTS idx_waitlist_product_created ON public.waitlist_entries(product_id, created_at DESC);

-- Add index on email for duplicate checking
CREATE INDEX IF NOT EXISTS idx_waitlist_email_unique ON public.waitlist_entries(email, product_id);

-- Add comment documentation
COMMENT ON TABLE public.waitlist_entries IS 'Stores waitlist signups for products. Prevents duplicates via unique constraint and validates email format at database level.';
COMMENT ON COLUMN public.waitlist_entries.id IS 'Unique identifier generated by database';
COMMENT ON COLUMN public.waitlist_entries.email IS 'User email address, validated with regex at database level';
COMMENT ON COLUMN public.waitlist_entries.product_id IS 'Reference to product (text, not foreign key as products are hardcoded)';
COMMENT ON COLUMN public.waitlist_entries.product_title IS 'Denormalized product title for reference, set at insertion time';
COMMENT ON COLUMN public.waitlist_entries.created_at IS 'Timestamp when user joined waitlist';
COMMENT ON COLUMN public.waitlist_entries.updated_at IS 'Timestamp of last update (reserved for future use)';
